version: '2'

services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/spring-boot
  production:
    image: ${DOCKER_USER_ID}/spring-boot:${BUILD_NUMBER}
    volumes:
      - /tmp
    restart: always
    ports:
      - 80:8080
    container_name: spring-boot