version: '3'

services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/spring-boot:${BUILD_NUMBER}
  production:
    image: ${DOCKER_USER_ID}/spring-boot:${BUILD_NUMBER}
    volumes:
      - /tmp
    restart: always
    ports:
      - 80:8080
    container_name: spring-boot
    command: ["bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /to-do-springboot.jar"]
