version: '3'

services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/spring-boot:latest
  production:
    image: ${DOCKER_USER_ID}/spring-boot:latest
    volumes:
      - /tmp
    restart: always
    ports:
      - 80:8080
    container_name: spring-boot