node {
	try {
	git poll:true, branch: 'master', credentialsId: 'github', url: 'https://github.com/zalkdo/spring.git'

    withCredentials([[$class: 'UsernamePasswordMultiBinding',
        credentialsId:'dockerhub',
        usernameVariable: 'DOCKER_USER_ID',
        passwordVariable: 'DOCKER_USER_PASSWORD']]){
           def customImage;
           stage('Pull') { // for display purposes
              git branch: 'master', credentialsId: 'github', url: 'https://github.com/zalkdo/spring.git'
           }
           stage('Gradle'){
              sh "pwd"
              dir('spring-boot'){
                sh "./gradlew clean build print"
              }
           }
           /*
           stage('Unit Test') {
               sh(script: 'docker-compose run --rm unit')
           }
           */
           stage('Build') {
				/*sh(script: 'docker build --force-rm=true -t ${DOCKER_USER_ID}/spring-boot:latest . ')*/
			   //customImage = docker.build("${DOCKER_USER_ID}/spring-boot:${BUILD_NUMBER}","spring-boot")
			   dir('spring-boot'){
			   	sh(script: 'docker-compose build --force-rm app')
			   }
           }
           stage('Tag'){
               sh(script: 'docker tag ${DOCKER_USER_ID}/spring-boot ${DOCKER_USER_ID}/spring-boot:${BUILD_NUMBER}')               
           }

           stage('Push'){
           	   dir('spring-boot'){
           	   	sh(script: 'docker login -u ${DOCKER_USER_ID} -p ${DOCKER_USER_PASSWORD}')
			   	sh(script: 'docker-compose push app')
			   	sh(script: 'docker-compose push lastest')
			   }
           /*
           	   docker.withRegistry("https://registry.hub.docker.com", "dockerhub"){
				   customImage.push()
				   customImage.push('latest')           	       
           	   }
           */
           }
           stage('Deploy') {
           		dir('spring-boot'){
           			sh(script: 'docker-compose up -d production')
           		}
        		/*try{
        		    sh(script: 'docker stop spring-boot')
        		    sh(script: 'docker rm spring-boot')
        		} catch(e) {
        		      echo "No ${DOCKER_USER_ID}/spring-boot container exists"
        		}
				sh(script : '''docker run -d -p 80:8080 --name spring-boot ${DOCKER_USER_ID}/spring-boot:${BUILD_NUMBER}''')
				*/
           }
        }
	} catch (e) {
	    // If there was an exception thrown, the build failed
	    currentBuild.result = "FAILED"
	    throw e
  	} finally {
		// Success or failure, always send notifications
    	notifyBuild(currentBuild.result)
  	}



/*
    post {
        success {
            slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
        }
        failure {
            slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
        }
    }
*/
}

def notifyBuild(String buildStatus = 'STARTED') {
  // build status of null means successful
  buildStatus =  buildStatus ?: 'SUCCESSFUL'

  // Default values
  def colorName = 'RED'
  def colorCode = '#FF0000'
  def subject = "${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
  def summary = "${subject} (${env.BUILD_URL})"

  // Override default values based on build status
  if (buildStatus == 'STARTED') {
    color = 'YELLOW'
    colorCode = '#FFFF00'
  } else if (buildStatus == 'SUCCESSFUL') {
    color = 'GREEN'
    colorCode = '#00FF00'
  } else {
    color = 'RED'
    colorCode = '#FF0000'
  }

  // Send notifications
  slackSend (color: colorCode, message: summary)
}