node {
	git poll:true, branch: 'master', credentialsId: 'github', url: 'https://github.com/zalkdo/spring.git'

    withCredentials([[$class: 'UsernamePasswordMultiBinding',
        credentialsId:'dockerhub',
        usernameVariable: 'DOCKER_USER_ID',
        passwordVariable: 'DOCKER_USER_PASSWORD']]){
           stage('Pull') { // for display purposes
              git branch: 'master', credentialsId: 'github', url: 'https://github.com/zalkdo/spring.git'
           }
           stage('Gradle'){
              sh "pwd"
              dir('spring-boot'){
                sh "./gradlew clean print"
              }
           }
           /*
           stage('Unit Test') {
               sh(script: 'docker-compose run --rm unit')
           }
           */
           stage('Docker') {
            /*sh(script: 'docker build --force-rm=true -t ${DOCKER_USER_ID}/spring-boot:latest . ')*/
            def customImage = docker.build("${DOCKER_USER_ID}/spring-boot:${BUILD_NUMBER}","spring-boot") 
           }
           stage('Push'){
           	   customImage.push()
               customImage.push('latest')
           }
           stage('Deploy') {
        
           }
        }

}
